# Generated by Django 4.0.3 on 2022-04-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inOut', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
